// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPdRMcFUQBeid_31D6q8_RuNoUogl3OtI',
    appId: '1:318859429456:web:a5971601a6458ba8d67355',
    messagingSenderId: '318859429456',
    projectId: 'damtrivia',
    authDomain: 'damtrivia.firebaseapp.com',
    storageBucket: 'damtrivia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyJQx01yPpBSW-kN54AgP0Y0lDH6-Fgss',
    appId: '1:318859429456:android:7fc2e057c011b9efd67355',
    messagingSenderId: '318859429456',
    projectId: 'damtrivia',
    storageBucket: 'damtrivia.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPdRMcFUQBeid_31D6q8_RuNoUogl3OtI',
    appId: '1:318859429456:web:190a6b5b30d8440cd67355',
    messagingSenderId: '318859429456',
    projectId: 'damtrivia',
    authDomain: 'damtrivia.firebaseapp.com',
    storageBucket: 'damtrivia.firebasestorage.app',
  );
}
